- platform: template
  sensors:
    anwesenheit:
      friendly_name: Anwesenheit
      value_template: >-
        {%- if is_state("device_tracker.handy_mni", "home")
            or is_state("device_tracker.handy_khi", "home")
            or is_state("device_tracker.tv_wohnzimmer", "home")
        -%}
        True
        {%- else -%}
        False
        {%- endif %}
      entity_id:
        - device_tracker.handy_mni
        - device_tracker.handy_khi
        - device_tracker.tv_wohnzimmer
