- platform: template
  sensors:
    mistwetter:
      friendly_name: Mistwetter
      device_class: light
      value_template: >-
        {%- if (is_state('sun.sun', 'above_horizon')
               and (states('sensor.dark_sky_precip_intensity') | float > 1
                      or (states('sensor.dark_sky_cloud_coverage') |  float > 90
                          and states('sun.sun.attributes.elevation') < 20.0)
                      )
                )
            -%}
        True
        {%- else -%}
        False
        {%- endif %}
      entity_id:
        - sensor.dark_sky_precip_intensity
        - sensor.dark_sky_cloud_coverage
        - sun.sun