homeassistant:
  name: Home
  latitude: !secret lat
  longitude: !secret long
  elevation: 0
  unit_system: metric
  time_zone: Europe/Berlin

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

updater:
  include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:


group: !include groups.yaml
automation: !include automations.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml
light: !include lights.yaml
mqtt: !include mqtt.yaml

# Text to speech
tts:
  - platform: google
    cache: true
    cache_dir: /home/homeassistant/.homeassistant/tts
    time_memory: 300

pilight:
  host: 127.0.0.1
  port: 5000

media_player:
  - platform: cast
    host: !secret IP_chromcast
  - platform: firetv
  
emulated_hue:
  host_ip: !secret IP_rpi-server
  expose_by_default: false
  listen_port: 80
  


