- platform: mqtt
  name: Wohnzimmer
  state_topic: "stat/sonoff-wohnzimmer/POWER"
  command_topic: "cmnd/sonoff-wohnzimmer/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: false

- platform: mqtt
  name: Arbeitszimmer
  state_topic: "stat/sonoff-arbeitszimmer/POWER"
  command_topic: "cmnd/sonoff-arbeitszimmer/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: false
  
- platform: mqtt
  name: Kuechenschrank
  state_topic: "stat/sonoff-kuechenschrank/POWER"
  command_topic: "cmnd/sonoff-kuechenschrank/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: false
  
- platform: mqtt
  name: Kueche
  state_topic: "stat/sonoff-kueche/POWER"
  command_topic: "cmnd/sonoff-kueche/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: false
  
- platform: limitlessled
  bridges:
    - host: 192.168.178.37
      port: 5987
      groups:
      - number: 1
        type: rgbw
        name: Balkon
        fade: on
