default_view:
  name: Home
  view: yes
  icon: mdi:home-assistant
  entities:
    - group.default_anwesenheit
    - camera.dom

default_anwesenheit:
  name: Anwesenheit
  entities:
    - device_tracker.mni_mni
    - device_tracker.khi_khi
    - sensor.arbeitsweg_kirstin
    - sensor.arbeitsweg_markus