- platform: wunderground
  api_key: !secret wundergroud_api_key
  lang: DL
  monitored_conditions:
    # - alerts
    - weather
    # - temp_c
    # - feelslike_c
    # - heat_index_c
    # - wind_kph
    # - relative_humidity
    # - visibility_km
    - UV
    # - pressure_mb
    - weather_1h
    - weather_1d_metric
    - weather_1n_metric
    # - weather_2d_metric
    # - weather_2n_metric
    # - weather_3d_metric
    # - weather_3n_metric
    - precip_today_metric
    - precip_today_string
    # - precip_1d
    # - precip_1d_mm
    