- alias: Abendbeleuchtung automatisch an
  trigger:
    - platform: sun
      event: sunset
      offset: "-00:20:00"
  action:
    service: homeassistant.turn_on
    entity_id: group.lights_evening

- alias: Abendbeleuchtung automatisch aus
  trigger:
    - platform: time
      at: '01:00:00'
  action:
    service: homeassistant.turn_off
    entity_id: group.lights_evening
