- alias: 'Alle Abwesend'
  trigger:
    - platform: state
      entity_id: binary_sensor.anwesenheit
      to: 'not_home'

  condition:
    - condition: state
      entity_id: binary_sensor.anwesenheit
      state: 'not_home'
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'

  action:
    - service: switch.turn_off
    - service: light.turn_off
    - service: notify.telegram
      data:
        message: "Alle Abwesend, alle Lichter wurden ausgeschaltet."