hide_entity: True 
trigger:
  platform: mqtt
  topic: "tele/sonoff-wohnzimmer/LWT"
  payload: "Offline"
action:
   service: mqtt.publish
   data:
       topic : "stat/sonoff-wohnzimmer/POWER"
       payload : "OFF"