- alias: Weihnachtsbeleuchtung automatisch an
  trigger:
    - platform: sun
      event: sunset
      offset: "-00:45:00"
  action:
    service: homeassistant.turn_on
    entity_id: group.lights_christmas

- alias: Weihnachtsbeleuchtung automatisch aus
  trigger:
    - platform: time
      at: '00:00:00'
  action:
    service: homeassistant.turn_off
    entity_id: group.lights_christmas
